package com.rkosistemas.com.model;
// Generated 15-nov-2018 14:23:45 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name="empleado"
    ,schema="dbo"
    ,catalog="restoitsco"
)
public class Empleado  implements java.io.Serializable {


     private int empleadoId;
     private Cargo cargo;
     private Empresa empresa;
     private String empleadoPrimerNombre;
     private String empleadoSegundoNombre;
     private String empleadoPrimerApellido;
     private String empleadoSegundoApellido;
     private Character empleadoTipoDni;
     private String empleadoDni;
     private Character empleadoEstadoCivil;
     private String empleadoNombreConyugue;
     private Character empleadoSexo;
     private Date empleadoFechaCreacion;
     private Date empleadoFechaModificacion;
     private Character empleadoEstado;
     private Set usuarios = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(int empleadoId) {
        this.empleadoId = empleadoId;
    }
    public Empleado(int empleadoId, Cargo cargo, Empresa empresa, String empleadoPrimerNombre, String empleadoSegundoNombre, String empleadoPrimerApellido, String empleadoSegundoApellido, Character empleadoTipoDni, String empleadoDni, Character empleadoEstadoCivil, String empleadoNombreConyugue, Character empleadoSexo, Date empleadoFechaCreacion, Date empleadoFechaModificacion, Character empleadoEstado, Set usuarios) {
       this.empleadoId = empleadoId;
       this.cargo = cargo;
       this.empresa = empresa;
       this.empleadoPrimerNombre = empleadoPrimerNombre;
       this.empleadoSegundoNombre = empleadoSegundoNombre;
       this.empleadoPrimerApellido = empleadoPrimerApellido;
       this.empleadoSegundoApellido = empleadoSegundoApellido;
       this.empleadoTipoDni = empleadoTipoDni;
       this.empleadoDni = empleadoDni;
       this.empleadoEstadoCivil = empleadoEstadoCivil;
       this.empleadoNombreConyugue = empleadoNombreConyugue;
       this.empleadoSexo = empleadoSexo;
       this.empleadoFechaCreacion = empleadoFechaCreacion;
       this.empleadoFechaModificacion = empleadoFechaModificacion;
       this.empleadoEstado = empleadoEstado;
       this.usuarios = usuarios;
    }
   
     @Id 

    
    @Column(name="empleadoId", unique=true, nullable=false)
    public int getEmpleadoId() {
        return this.empleadoId;
    }
    
    public void setEmpleadoId(int empleadoId) {
        this.empleadoId = empleadoId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cargoId")
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empresaId")
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="empleadoPrimerNombre", length=150)
    public String getEmpleadoPrimerNombre() {
        return this.empleadoPrimerNombre;
    }
    
    public void setEmpleadoPrimerNombre(String empleadoPrimerNombre) {
        this.empleadoPrimerNombre = empleadoPrimerNombre;
    }

    
    @Column(name="empleadoSegundoNombre", length=150)
    public String getEmpleadoSegundoNombre() {
        return this.empleadoSegundoNombre;
    }
    
    public void setEmpleadoSegundoNombre(String empleadoSegundoNombre) {
        this.empleadoSegundoNombre = empleadoSegundoNombre;
    }

    
    @Column(name="empleadoPrimerApellido", length=150)
    public String getEmpleadoPrimerApellido() {
        return this.empleadoPrimerApellido;
    }
    
    public void setEmpleadoPrimerApellido(String empleadoPrimerApellido) {
        this.empleadoPrimerApellido = empleadoPrimerApellido;
    }

    
    @Column(name="empleadoSegundoApellido", length=150)
    public String getEmpleadoSegundoApellido() {
        return this.empleadoSegundoApellido;
    }
    
    public void setEmpleadoSegundoApellido(String empleadoSegundoApellido) {
        this.empleadoSegundoApellido = empleadoSegundoApellido;
    }

    
    @Column(name="empleadoTipoDni", length=1)
    public Character getEmpleadoTipoDni() {
        return this.empleadoTipoDni;
    }
    
    public void setEmpleadoTipoDni(Character empleadoTipoDni) {
        this.empleadoTipoDni = empleadoTipoDni;
    }

    
    @Column(name="empleadoDni", length=50)
    public String getEmpleadoDni() {
        return this.empleadoDni;
    }
    
    public void setEmpleadoDni(String empleadoDni) {
        this.empleadoDni = empleadoDni;
    }

    
    @Column(name="empleadoEstadoCivil", length=1)
    public Character getEmpleadoEstadoCivil() {
        return this.empleadoEstadoCivil;
    }
    
    public void setEmpleadoEstadoCivil(Character empleadoEstadoCivil) {
        this.empleadoEstadoCivil = empleadoEstadoCivil;
    }

    
    @Column(name="empleadoNombreConyugue", length=500)
    public String getEmpleadoNombreConyugue() {
        return this.empleadoNombreConyugue;
    }
    
    public void setEmpleadoNombreConyugue(String empleadoNombreConyugue) {
        this.empleadoNombreConyugue = empleadoNombreConyugue;
    }

    
    @Column(name="empleadoSexo", length=1)
    public Character getEmpleadoSexo() {
        return this.empleadoSexo;
    }
    
    public void setEmpleadoSexo(Character empleadoSexo) {
        this.empleadoSexo = empleadoSexo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="empleadoFechaCreacion", length=23)
    public Date getEmpleadoFechaCreacion() {
        return this.empleadoFechaCreacion;
    }
    
    public void setEmpleadoFechaCreacion(Date empleadoFechaCreacion) {
        this.empleadoFechaCreacion = empleadoFechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="empleadoFechaModificacion", length=23)
    public Date getEmpleadoFechaModificacion() {
        return this.empleadoFechaModificacion;
    }
    
    public void setEmpleadoFechaModificacion(Date empleadoFechaModificacion) {
        this.empleadoFechaModificacion = empleadoFechaModificacion;
    }

    
    @Column(name="empleadoEstado", length=1)
    public Character getEmpleadoEstado() {
        return this.empleadoEstado;
    }
    
    public void setEmpleadoEstado(Character empleadoEstado) {
        this.empleadoEstado = empleadoEstado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empleado")
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


