package com.rkosistemas.com.model;
// Generated 15-nov-2018 14:23:45 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Perfilusuario generated by hbm2java
 */
@Entity
@Table(name="perfilusuario"
    ,schema="dbo"
    ,catalog="restoitsco"
)
public class Perfilusuario  implements java.io.Serializable {


     private int perfilusuarioid;
     private Perfil perfil;
     private Integer usuarioid;
     private Date perfilusuarioFechaCreacion;
     private Date perfilusuarioFechaModificacion;
     private Serializable perfilusuarioEstado;

    public Perfilusuario() {
    }

	
    public Perfilusuario(int perfilusuarioid) {
        this.perfilusuarioid = perfilusuarioid;
    }
    public Perfilusuario(int perfilusuarioid, Perfil perfil, Integer usuarioid, Date perfilusuarioFechaCreacion, Date perfilusuarioFechaModificacion, Serializable perfilusuarioEstado) {
       this.perfilusuarioid = perfilusuarioid;
       this.perfil = perfil;
       this.usuarioid = usuarioid;
       this.perfilusuarioFechaCreacion = perfilusuarioFechaCreacion;
       this.perfilusuarioFechaModificacion = perfilusuarioFechaModificacion;
       this.perfilusuarioEstado = perfilusuarioEstado;
    }
   
     @Id 

    
    @Column(name="perfilusuarioid", unique=true, nullable=false)
    public int getPerfilusuarioid() {
        return this.perfilusuarioid;
    }
    
    public void setPerfilusuarioid(int perfilusuarioid) {
        this.perfilusuarioid = perfilusuarioid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="perfilid")
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }

    
    @Column(name="usuarioid")
    public Integer getUsuarioid() {
        return this.usuarioid;
    }
    
    public void setUsuarioid(Integer usuarioid) {
        this.usuarioid = usuarioid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="perfilusuarioFechaCreacion", length=23)
    public Date getPerfilusuarioFechaCreacion() {
        return this.perfilusuarioFechaCreacion;
    }
    
    public void setPerfilusuarioFechaCreacion(Date perfilusuarioFechaCreacion) {
        this.perfilusuarioFechaCreacion = perfilusuarioFechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="perfilusuarioFechaModificacion", length=23)
    public Date getPerfilusuarioFechaModificacion() {
        return this.perfilusuarioFechaModificacion;
    }
    
    public void setPerfilusuarioFechaModificacion(Date perfilusuarioFechaModificacion) {
        this.perfilusuarioFechaModificacion = perfilusuarioFechaModificacion;
    }

    
    @Column(name="perfilusuarioEstado")
    public Serializable getPerfilusuarioEstado() {
        return this.perfilusuarioEstado;
    }
    
    public void setPerfilusuarioEstado(Serializable perfilusuarioEstado) {
        this.perfilusuarioEstado = perfilusuarioEstado;
    }




}


