package com.rkosistemas.model;
// Generated 15-nov-2018 14:23:45 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name="empresa"
    ,schema="dbo"
    ,catalog="restoitsco"
)
public class Empresa  implements java.io.Serializable {


     private int empresaId;
     private String empresaRazonSocial;
     private String empresaRuc;
     private String empresaDireccion;
     private String empresaTelefono;
     private String empresaCorreo;
     private Date empresaFechaCreacion;
     private Date empresaFechaModificacion;
     private Character empresaEstado;
     private Set empleados = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(int empresaId) {
        this.empresaId = empresaId;
    }
    public Empresa(int empresaId, String empresaRazonSocial, String empresaRuc, String empresaDireccion, String empresaTelefono, String empresaCorreo, Date empresaFechaCreacion, Date empresaFechaModificacion, Character empresaEstado, Set empleados) {
       this.empresaId = empresaId;
       this.empresaRazonSocial = empresaRazonSocial;
       this.empresaRuc = empresaRuc;
       this.empresaDireccion = empresaDireccion;
       this.empresaTelefono = empresaTelefono;
       this.empresaCorreo = empresaCorreo;
       this.empresaFechaCreacion = empresaFechaCreacion;
       this.empresaFechaModificacion = empresaFechaModificacion;
       this.empresaEstado = empresaEstado;
       this.empleados = empleados;
    }
   
     @Id 

    
    @Column(name="empresaId", unique=true, nullable=false)
    public int getEmpresaId() {
        return this.empresaId;
    }
    
    public void setEmpresaId(int empresaId) {
        this.empresaId = empresaId;
    }

    
    @Column(name="empresaRazonSocial", length=250)
    public String getEmpresaRazonSocial() {
        return this.empresaRazonSocial;
    }
    
    public void setEmpresaRazonSocial(String empresaRazonSocial) {
        this.empresaRazonSocial = empresaRazonSocial;
    }

    
    @Column(name="empresaRuc", length=15)
    public String getEmpresaRuc() {
        return this.empresaRuc;
    }
    
    public void setEmpresaRuc(String empresaRuc) {
        this.empresaRuc = empresaRuc;
    }

    
    @Column(name="empresaDireccion", length=250)
    public String getEmpresaDireccion() {
        return this.empresaDireccion;
    }
    
    public void setEmpresaDireccion(String empresaDireccion) {
        this.empresaDireccion = empresaDireccion;
    }

    
    @Column(name="empresaTelefono", length=15)
    public String getEmpresaTelefono() {
        return this.empresaTelefono;
    }
    
    public void setEmpresaTelefono(String empresaTelefono) {
        this.empresaTelefono = empresaTelefono;
    }

    
    @Column(name="empresaCorreo", length=200)
    public String getEmpresaCorreo() {
        return this.empresaCorreo;
    }
    
    public void setEmpresaCorreo(String empresaCorreo) {
        this.empresaCorreo = empresaCorreo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="empresaFechaCreacion", length=23)
    public Date getEmpresaFechaCreacion() {
        return this.empresaFechaCreacion;
    }
    
    public void setEmpresaFechaCreacion(Date empresaFechaCreacion) {
        this.empresaFechaCreacion = empresaFechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="empresaFechaModificacion", length=23)
    public Date getEmpresaFechaModificacion() {
        return this.empresaFechaModificacion;
    }
    
    public void setEmpresaFechaModificacion(Date empresaFechaModificacion) {
        this.empresaFechaModificacion = empresaFechaModificacion;
    }

    
    @Column(name="empresaEstado", length=1)
    public Character getEmpresaEstado() {
        return this.empresaEstado;
    }
    
    public void setEmpresaEstado(Character empresaEstado) {
        this.empresaEstado = empresaEstado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }




}


