package com.rkosistemas.model;
// Generated 15-nov-2018 14:23:45 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="dbo"
    ,catalog="restoitsco"
)
public class Usuario  implements java.io.Serializable {


     private int usuarioId;
     private Empleado empleado;
     private String usuarioUsername;
     private String usuarioPassword;
     private Date usuarioFechaCreacion;
     private Date usuarioFechaModificacion;
     private Character usuarioEstado;

    public Usuario() {
    }

	
    public Usuario(int usuarioId) {
        this.usuarioId = usuarioId;
    }
    public Usuario(int usuarioId, Empleado empleado, String usuarioUsername, String usuarioPassword, Date usuarioFechaCreacion, Date usuarioFechaModificacion, Character usuarioEstado) {
       this.usuarioId = usuarioId;
       this.empleado = empleado;
       this.usuarioUsername = usuarioUsername;
       this.usuarioPassword = usuarioPassword;
       this.usuarioFechaCreacion = usuarioFechaCreacion;
       this.usuarioFechaModificacion = usuarioFechaModificacion;
       this.usuarioEstado = usuarioEstado;
    }
   
     @Id 

    
    @Column(name="usuarioId", unique=true, nullable=false)
    public int getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(int usuarioId) {
        this.usuarioId = usuarioId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empleadoId")
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    
    @Column(name="usuarioUsername", length=50)
    public String getUsuarioUsername() {
        return this.usuarioUsername;
    }
    
    public void setUsuarioUsername(String usuarioUsername) {
        this.usuarioUsername = usuarioUsername;
    }

    
    @Column(name="usuarioPassword", length=50)
    public String getUsuarioPassword() {
        return this.usuarioPassword;
    }
    
    public void setUsuarioPassword(String usuarioPassword) {
        this.usuarioPassword = usuarioPassword;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="usuarioFechaCreacion", length=23)
    public Date getUsuarioFechaCreacion() {
        return this.usuarioFechaCreacion;
    }
    
    public void setUsuarioFechaCreacion(Date usuarioFechaCreacion) {
        this.usuarioFechaCreacion = usuarioFechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="usuarioFechaModificacion", length=23)
    public Date getUsuarioFechaModificacion() {
        return this.usuarioFechaModificacion;
    }
    
    public void setUsuarioFechaModificacion(Date usuarioFechaModificacion) {
        this.usuarioFechaModificacion = usuarioFechaModificacion;
    }

    
    @Column(name="usuarioEstado", length=1)
    public Character getUsuarioEstado() {
        return this.usuarioEstado;
    }
    
    public void setUsuarioEstado(Character usuarioEstado) {
        this.usuarioEstado = usuarioEstado;
    }




}


